In [94]:
import sys
from pathlib import Path
import pandas as pd
from sqlalchemy import text
from research.db.connection import get_engine

# Root проекта
candidates = [Path.cwd(), Path.cwd().parent, Path.cwd().parent.parent]
root = next((p for p in candidates if (p / "pyproject.toml").exists()), Path.cwd())
if (root / "research").is_dir():
    sys.path.insert(0, str(root))

data_dir = root / "data" / "reconstructed"

In [95]:
# Путь к Parquet (подставь свой файл)
# data_dir из первой ячейки (root / data / reconstructed) — выполни её

# Путь к одному часовому parquet
parquet_path = data_dir / "BTC-USDT-SWAP" / "grid100ms" / "2026-03-22" / (
    "book_grid100ms_BTC-USDT-SWAP_2026-03-22_10-00-00__2026-03-22_11-00-00.parquet"
)
if not parquet_path.exists():
    found = sorted(data_dir.rglob("*.parquet"))
    parquet_path = found[0] if found else parquet_path
    if found:
        print("Файл по умолчанию не найден, загружаю:", parquet_path)

df = pd.read_parquet(parquet_path)
df

,ts_event,inst_id,anchor_snapshot_ts,reconstruction_mode,mid_px,spread_px,bid_px_01,bid_sz_01,bid_px_02,bid_sz_02,...,ask_px_06,ask_sz_06,ask_px_07,ask_sz_07,ask_px_08,ask_sz_08,ask_px_09,ask_sz_09,ask_px_10,ask_sz_10
0,2026-03-22 10:00:00+00:00,BTC-USDT-SWAP,2026-03-22 09:59:39.307000+00:00,grid_100ms,68780.05,0.1,68780.0,59.31,68779.9,6.56,...,68780.6,0.06,68780.7,0.08,68780.8,51.51,68780.9,0.01,68781.0,6.88
1,2026-03-22 10:00:00.100000+00:00,BTC-USDT-SWAP,2026-03-22 09:59:39.307000+00:00,grid_100ms,68780.05,0.1,68780.0,59.27,68779.9,6.56,...,68780.6,0.06,68780.7,0.08,68780.8,51.51,68780.9,0.01,68781.0,6.88
2,2026-03-22 10:00:00.200000+00:00,BTC-USDT-SWAP,2026-03-22 09:59:39.307000+00:00,grid_100ms,68780.05,0.1,68780.0,67.24,68779.9,6.56,...,68780.6,0.06,68780.7,0.08,68780.8,51.51,68780.9,0.01,68781.0,6.88
3,2026-03-22 10:00:00.300000+00:00,BTC-USDT-SWAP,2026-03-22 09:59:39.307000+00:00,grid_100ms,68780.05,0.1,68780.0,59.30,68779.9,6.56,...,68780.6,0.06,68780.7,0.08,68780.8,51.51,68780.9,0.01,68781.0,6.88
4,2026-03-22 10:00:00.400000+00:00,BTC-USDT-SWAP,2026-03-22 09:59:39.307000+00:00,grid_100ms,68780.05,0.1,68780.0,61.56,68779.9,6.56,...,68780.6,0.06,68780.7,0.08,68780.8,51.51,68780.9,0.01,68781.0,6.88
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35996,2026-03-22 10:59:59.600000+00:00,BTC-USDT-SWAP,2026-03-22 10:59:43.909000+00:00,grid_100ms,68600.55,0.1,68600.5,226.44,68600.4,0.06,...,68602.8,0.01,68603.1,0.01,68603.3,0.03,68603.8,0.01,68603.9,1.45
35997,2026-03-22 10:59:59.700000+00:00,BTC-USDT-SWAP,2026-03-22 10:59:43.909000+00:00,grid_100ms,68600.55,0.1,68600.5,226.37,68600.4,0.06,...,68602.8,0.01,68603.1,0.01,68603.3,0.03,68603.8,0.01,68603.9,1.45
35998,2026-03-22 10:59:59.800000+00:00,BTC-USDT-SWAP,2026-03-22 10:59:43.909000+00:00,grid_100ms,68600.55,0.1,68600.5,226.44,68600.4,0.06,...,68603.1,0.01,68603.3,0.03,68603.8,0.01,68603.9,0.03,68604.1,0.06
35999,2026-03-22 10:59:59.900000+00:00,BTC-USDT-SWAP,2026-03-22 10:59:43.909000+00:00,grid_100ms,68600.55,0.1,68600.5,226.44,68600.4,0.06,...,68603.1,0.01,68603.3,0.03,68603.8,0.01,68603.9,0.03,68604.1,0.06
36000,2026-03-22 11:00:00+00:00,BTC-USDT-SWAP,2026-03-22 10:59:43.909000+00:00,grid_100ms,68600.55,0.1,68600.5,226.44,68600.4,0.06,...,68603.1,0.01,68603.3,0.03,68603.8,0.01,68603.9,0.03,68604.1,0.06

In [80]:
df.columns

Index(['ts_event', 'inst_id', 'anchor_snapshot_ts', 'reconstruction_mode',
       'mid_px', 'spread_px', 'bid_px_01', 'bid_sz_01', 'bid_px_02',
       'bid_sz_02', 'bid_px_03', 'bid_sz_03', 'bid_px_04', 'bid_sz_04',
       'bid_px_05', 'bid_sz_05', 'bid_px_06', 'bid_sz_06', 'bid_px_07',
       'bid_sz_07', 'bid_px_08', 'bid_sz_08', 'bid_px_09', 'bid_sz_09',
       'bid_px_10', 'bid_sz_10', 'ask_px_01', 'ask_sz_01', 'ask_px_02',
       'ask_sz_02', 'ask_px_03', 'ask_sz_03', 'ask_px_04', 'ask_sz_04',
       'ask_px_05', 'ask_sz_05', 'ask_px_06', 'ask_sz_06', 'ask_px_07',
       'ask_sz_07', 'ask_px_08', 'ask_sz_08', 'ask_px_09', 'ask_sz_09',
       'ask_px_10', 'ask_sz_10'],
      dtype='object')

In [96]:
df.anchor_snapshot_ts.unique()

<DatetimeArray>
['2026-03-22 09:59:39.307000+00:00', '2026-03-22 10:00:09.907000+00:00',
 '2026-03-22 10:00:40.707000+00:00', '2026-03-22 10:01:11.407000+00:00',
 '2026-03-22 10:01:42.307000+00:00', '2026-03-22 10:02:13.007000+00:00',
 '2026-03-22 10:02:43.707000+00:00', '2026-03-22 10:03:14.407000+00:00',
 '2026-03-22 10:03:45.107000+00:00', '2026-03-22 10:04:16.507000+00:00',
 ...
 '2026-03-22 10:55:06.109000+00:00', '2026-03-22 10:55:36.909000+00:00',
 '2026-03-22 10:56:07.609000+00:00', '2026-03-22 10:56:39.709000+00:00',
 '2026-03-22 10:57:10.409000+00:00', '2026-03-22 10:57:40.909000+00:00',
 '2026-03-22 10:58:11.909000+00:00', '2026-03-22 10:58:42.509000+00:00',
 '2026-03-22 10:59:13.209000+00:00', '2026-03-22 10:59:43.909000+00:00']
Length: 118, dtype: datetime64[ns, UTC]

In [97]:
engine = get_engine()

import numpy as np
import pandas as pd
from sqlalchemy import text

# ============================================================
# CONFIG
# ============================================================

INST_ID = "BTC-USDT-SWAP"
DEPTH = 10
N_SAMPLES = 200          # сначала можно 50-200, потом 1000
RANDOM_SEED = 42

# если хочешь руками задать окно, оставь None чтобы брать из parquet
WINDOW_START = None
WINDOW_END = None


# ============================================================
# 1. PREPARE RECONSTRUCTED DF
# ============================================================

rec_df = df.copy()

rec_df["ts_event"] = pd.to_datetime(rec_df["ts_event"], utc=True, errors="coerce")
rec_df["anchor_snapshot_ts"] = pd.to_datetime(
    rec_df["anchor_snapshot_ts"], utc=True, errors="coerce"
)

rec_df = rec_df.sort_values("ts_event").reset_index(drop=True)

if rec_df["ts_event"].isna().all():
    raise ValueError("Колонка ts_event в parquet не распарсилась")

if WINDOW_START is None:
    window_start = rec_df["ts_event"].min()
else:
    window_start = pd.Timestamp(WINDOW_START, tz="UTC")

if WINDOW_END is None:
    window_end = rec_df["ts_event"].max()
else:
    window_end = pd.Timestamp(WINDOW_END, tz="UTC")

print("window_start:", window_start)
print("window_end  :", window_end)
print("reconstructed rows:", len(rec_df))


# ============================================================
# 2. HELPERS
# ============================================================

def reconstructed_row_to_long(rec_row: pd.Series, depth: int = 10) -> pd.DataFrame:
    rows = []

    for side in ["bid", "ask"]:
        for level in range(1, depth + 1):
            px_col = f"{side}_px_{level:02d}"
            sz_col = f"{side}_sz_{level:02d}"

            if px_col not in rec_row.index or sz_col not in rec_row.index:
                continue

            px = rec_row[px_col]
            sz = rec_row[sz_col]

            if pd.isna(px) and pd.isna(sz):
                continue

            rows.append(
                {
                    "side": side,
                    "level": level,
                    "rec_px": float(px) if pd.notna(px) else np.nan,
                    "rec_sz": float(sz) if pd.notna(sz) else np.nan,
                }
            )

    out = pd.DataFrame(rows)
    if out.empty:
        raise ValueError("Из reconstructed row не удалось собрать уровни")

    return out.sort_values(["side", "level"]).reset_index(drop=True)


def normalize_real_snapshot_df(real_snapshot_df: pd.DataFrame, depth: int = 10) -> pd.DataFrame:
    real = real_snapshot_df.copy()

    rename_map = {}
    if "price" in real.columns:
        rename_map["price"] = "real_px"
    elif "px" in real.columns:
        rename_map["px"] = "real_px"

    if "size" in real.columns:
        rename_map["size"] = "real_sz"
    elif "sz" in real.columns:
        rename_map["sz"] = "real_sz"

    real = real.rename(columns=rename_map)

    required = ["side", "level", "real_px", "real_sz"]
    missing = [c for c in required if c not in real.columns]
    if missing:
        raise ValueError(f"В real_snapshot_df не хватает колонок: {missing}")

    real["side"] = real["side"].astype(str).str.strip().str.lower()

    side_map = {
        "bid": "bid",
        "bids": "bid",
        "buy": "bid",
        "1": "bid",
        "ask": "ask",
        "asks": "ask",
        "sell": "ask",
        "2": "ask",
    }
    real["side"] = real["side"].map(side_map).fillna(real["side"])

    real["level"] = pd.to_numeric(real["level"], errors="coerce")
    real["real_px"] = pd.to_numeric(real["real_px"], errors="coerce")
    real["real_sz"] = pd.to_numeric(real["real_sz"], errors="coerce")

    real = real.loc[real["side"].isin(["bid", "ask"])].copy()
    if real.empty:
        raise ValueError("После нормализации real_snapshot_df пустой")

    real["level"] = real["level"].astype(int)

    real = real[["side", "level", "real_px", "real_sz"]]
    real = real.sort_values(["side", "level"]).reset_index(drop=True)

    return real


def build_orderbook_comparison(real_long_df: pd.DataFrame, rec_long_df: pd.DataFrame) -> pd.DataFrame:
    cmp_df = pd.merge(
        rec_long_df,
        real_long_df,
        on=["side", "level"],
        how="outer",
    )

    cmp_df["px_diff"] = (cmp_df["rec_px"] - cmp_df["real_px"]).abs()
    cmp_df["sz_diff"] = (cmp_df["rec_sz"] - cmp_df["real_sz"]).abs()

    cmp_df["px_match"] = (
        cmp_df["rec_px"].notna()
        & cmp_df["real_px"].notna()
        & (cmp_df["px_diff"] <= 1e-9)
    )

    cmp_df["sz_match"] = (
        cmp_df["rec_sz"].notna()
        & cmp_df["real_sz"].notna()
        & (cmp_df["sz_diff"] <= 1e-9)
    )

    cmp_df = cmp_df.sort_values(["side", "level"]).reset_index(drop=True)
    return cmp_df


def build_summary(compare_df: pd.DataFrame, snapshot_ts: pd.Timestamp, reconstructed_ts: pd.Timestamp) -> dict:
    bid1 = compare_df[(compare_df["side"] == "bid") & (compare_df["level"] == 1)]
    ask1 = compare_df[(compare_df["side"] == "ask") & (compare_df["level"] == 1)]

    if bid1.empty or ask1.empty:
        raise ValueError("Не найден bid/ask level 1")

    top_bid_rec = float(bid1["rec_px"].iloc[0]) if pd.notna(bid1["rec_px"].iloc[0]) else np.nan
    top_bid_real = float(bid1["real_px"].iloc[0]) if pd.notna(bid1["real_px"].iloc[0]) else np.nan
    top_ask_rec = float(ask1["rec_px"].iloc[0]) if pd.notna(ask1["rec_px"].iloc[0]) else np.nan
    top_ask_real = float(ask1["real_px"].iloc[0]) if pd.notna(ask1["real_px"].iloc[0]) else np.nan

    return {
        "snapshot_ts": snapshot_ts,
        "reconstructed_ts": reconstructed_ts,
        "time_delta_ms": float((snapshot_ts - reconstructed_ts).total_seconds() * 1000.0),
        "top_bid_rec": top_bid_rec,
        "top_bid_real": top_bid_real,
        "top_ask_rec": top_ask_rec,
        "top_ask_real": top_ask_real,
        "top_bid_diff": float(abs(top_bid_rec - top_bid_real)) if pd.notna(top_bid_rec) and pd.notna(top_bid_real) else np.nan,
        "top_ask_diff": float(abs(top_ask_rec - top_ask_real)) if pd.notna(top_ask_rec) and pd.notna(top_ask_real) else np.nan,
        "px_match_count": int(compare_df["px_match"].sum()),
        "sz_match_count": int(compare_df["sz_match"].sum()),
        "max_px_diff": float(compare_df["px_diff"].max()) if compare_df["px_diff"].notna().any() else np.nan,
        "max_sz_diff": float(compare_df["sz_diff"].max()) if compare_df["sz_diff"].notna().any() else np.nan,
        "px_mismatches": int((~compare_df["px_match"]).sum()),
        "sz_mismatches": int((~compare_df["sz_match"]).sum()),
    }


def compute_orderbook_quality_metrics(compare_df: pd.DataFrame, top_n: int = 5) -> dict:
    top = compare_df.loc[compare_df["level"] <= top_n].copy()

    bid1 = compare_df[(compare_df["side"] == "bid") & (compare_df["level"] == 1)]
    ask1 = compare_df[(compare_df["side"] == "ask") & (compare_df["level"] == 1)]

    if bid1.empty or ask1.empty:
        raise ValueError("Нет best bid/ask level=1")

    best_bid_rec = float(bid1["rec_px"].iloc[0])
    best_bid_real = float(bid1["real_px"].iloc[0])
    best_ask_rec = float(ask1["rec_px"].iloc[0])
    best_ask_real = float(ask1["real_px"].iloc[0])

    mid_rec = (best_bid_rec + best_ask_rec) / 2.0
    mid_real = (best_bid_real + best_ask_real) / 2.0
    mid_price_diff = abs(mid_rec - mid_real)

    bid_top = top[top["side"] == "bid"]
    ask_top = top[top["side"] == "ask"]

    top_bid_rec = float(bid_top["rec_sz"].sum())
    top_bid_real = float(bid_top["real_sz"].sum())
    top_ask_rec = float(ask_top["rec_sz"].sum())
    top_ask_real = float(ask_top["real_sz"].sum())

    topN_liquidity_diff_abs = abs(top_bid_rec - top_bid_real) + abs(top_ask_rec - top_ask_real)

    topN_liquidity_diff_pct = (
        abs(top_bid_rec - top_bid_real) / max(top_bid_real, 1e-9)
        + abs(top_ask_rec - top_ask_real) / max(top_ask_real, 1e-9)
    ) / 2.0

    denom_rec = max(top_bid_rec + top_ask_rec, 1e-9)
    denom_real = max(top_bid_real + top_ask_real, 1e-9)

    imbalance_rec = (top_bid_rec - top_ask_rec) / denom_rec
    imbalance_real = (top_bid_real - top_ask_real) / denom_real
    imbalance_diff = abs(imbalance_rec - imbalance_real)

    return {
        "mid_rec": mid_rec,
        "mid_real": mid_real,
        "mid_price_diff": mid_price_diff,
        "top_bid_rec": top_bid_rec,
        "top_bid_real": top_bid_real,
        "top_ask_rec": top_ask_rec,
        "top_ask_real": top_ask_real,
        "topN_liquidity_diff_abs": topN_liquidity_diff_abs,
        "topN_liquidity_diff_pct": topN_liquidity_diff_pct,
        "imbalance_rec": imbalance_rec,
        "imbalance_real": imbalance_real,
        "imbalance_diff": imbalance_diff,
    }


def get_rec_row_at_or_before(rec_df: pd.DataFrame, snapshot_ts: pd.Timestamp) -> pd.Series:
    candidates = rec_df.loc[rec_df["ts_event"] <= snapshot_ts]
    if candidates.empty:
        raise ValueError("Нет reconstructed state не позже snapshot_ts")
    return candidates.iloc[-1].copy()


# ============================================================
# 3. LOAD REAL SNAPSHOT TIMESTAMPS IN WINDOW
# ============================================================

window_start_ms = int(window_start.timestamp() * 1000)
window_end_ms = int(window_end.timestamp() * 1000)

snapshot_candidates_sql = text(
    """
    SELECT DISTINCT
        ts_event_ms,
        to_timestamp(ts_event_ms / 1000.0) AT TIME ZONE 'UTC' AS ts_event_utc
    FROM okx_raw.orderbook_snapshots
    WHERE instid = :inst_id
      AND ts_event_ms BETWEEN :start_ms AND :end_ms
    ORDER BY ts_event_ms
    """
)

snapshot_levels_sql = text(
    """
    SELECT
        *,
        to_timestamp(ts_event_ms / 1000.0) AT TIME ZONE 'UTC' AS ts_event_utc
    FROM okx_raw.orderbook_snapshots
    WHERE instid = :inst_id
      AND ts_event_ms = :snapshot_ms
    ORDER BY side, level
    """
)

snapshot_candidates_df = pd.read_sql_query(
    snapshot_candidates_sql,
    engine,
    params={
        "inst_id": INST_ID,
        "start_ms": window_start_ms,
        "end_ms": window_end_ms,
    },
)

if snapshot_candidates_df.empty:
    raise ValueError("В окне parquet не найдено ни одного real snapshot")

snapshot_candidates_df["ts_event_utc"] = pd.to_datetime(
    snapshot_candidates_df["ts_event_utc"], utc=True, errors="coerce"
)

print("real snapshots in window:", len(snapshot_candidates_df))

sample_n = min(N_SAMPLES, len(snapshot_candidates_df))
sampled_snapshots_df = snapshot_candidates_df.sample(
    n=sample_n,
    random_state=RANDOM_SEED,
).sort_values("ts_event_ms").reset_index(drop=True)

print("sampled snapshots:", len(sampled_snapshots_df))
display(sampled_snapshots_df.head())


# ============================================================
# 4. VALIDATE MANY POINTS
# ============================================================

results = []
bad_cases = []

for i, row in sampled_snapshots_df.iterrows():
    snapshot_ms = int(row["ts_event_ms"])
    snapshot_ts = pd.Timestamp(row["ts_event_utc"])

    try:
        # real snapshot
        real_snapshot_df = pd.read_sql_query(
            snapshot_levels_sql,
            engine,
            params={
                "inst_id": INST_ID,
                "snapshot_ms": snapshot_ms,
            },
        )

        real_long_df = normalize_real_snapshot_df(real_snapshot_df, depth=DEPTH)

        # reconstructed row
        rec_row = get_rec_row_at_or_before(rec_df, snapshot_ts)
        reconstructed_ts = pd.Timestamp(rec_row["ts_event"])
        anchor_snapshot_ts = pd.Timestamp(rec_row["anchor_snapshot_ts"]) if "anchor_snapshot_ts" in rec_row.index else pd.NaT

        rec_long_df = reconstructed_row_to_long(rec_row, depth=DEPTH)

        # compare
        compare_df = build_orderbook_comparison(real_long_df, rec_long_df)
        summary = build_summary(compare_df, snapshot_ts, reconstructed_ts)
        quality = compute_orderbook_quality_metrics(compare_df, top_n=5)

        result_row = {
            "snapshot_ms": snapshot_ms,
            "snapshot_ts": snapshot_ts,
            "reconstructed_ts": reconstructed_ts,
            "anchor_snapshot_ts": anchor_snapshot_ts,
            "time_delta_ms": summary["time_delta_ms"],
            "px_match_count": summary["px_match_count"],
            "sz_match_count": summary["sz_match_count"],
            "px_mismatches": summary["px_mismatches"],
            "sz_mismatches": summary["sz_mismatches"],
            "max_px_diff": summary["max_px_diff"],
            "max_sz_diff": summary["max_sz_diff"],
            "top_bid_diff": summary["top_bid_diff"],
            "top_ask_diff": summary["top_ask_diff"],
            "mid_price_diff": quality["mid_price_diff"],
            "top5_liquidity_diff_abs": quality["topN_liquidity_diff_abs"],
            "top5_liquidity_diff_pct": quality["topN_liquidity_diff_pct"],
            "imbalance_diff": quality["imbalance_diff"],
            "status": "ok",
            "error": None,
        }
        results.append(result_row)

        # сохраним кейсы с худшими ошибками для ручного просмотра
        if (
            result_row["max_px_diff"] > 0
            or result_row["top5_liquidity_diff_pct"] > 0.05
            or result_row["imbalance_diff"] > 0.05
        ):
            bad_cases.append(
                {
                    "snapshot_ts": snapshot_ts,
                    "compare_df": compare_df.copy(),
                    "summary": summary,
                    "quality": quality,
                }
            )

    except Exception as e:
        results.append(
            {
                "snapshot_ms": snapshot_ms,
                "snapshot_ts": snapshot_ts,
                "reconstructed_ts": pd.NaT,
                "anchor_snapshot_ts": pd.NaT,
                "time_delta_ms": np.nan,
                "px_match_count": np.nan,
                "sz_match_count": np.nan,
                "px_mismatches": np.nan,
                "sz_mismatches": np.nan,
                "max_px_diff": np.nan,
                "max_sz_diff": np.nan,
                "top_bid_diff": np.nan,
                "top_ask_diff": np.nan,
                "mid_price_diff": np.nan,
                "top5_liquidity_diff_abs": np.nan,
                "top5_liquidity_diff_pct": np.nan,
                "imbalance_diff": np.nan,
                "status": "error",
                "error": str(e),
            }
        )

results_df = pd.DataFrame(results)
print("validated points:", len(results_df))
display(results_df.head())


# ============================================================
# 5. KEEP ONLY SUCCESSFUL CASES
# ============================================================

ok_results_df = results_df.loc[results_df["status"] == "ok"].copy()

if ok_results_df.empty:
    raise ValueError("Все проверки упали, смотри results_df['error']")

print("successful validations:", len(ok_results_df))
print("failed validations     :", (results_df["status"] == "error").sum())


# ============================================================
# 6. SUMMARY STATS: mean / median / p95 / worst
# ============================================================

metric_cols = [
    "time_delta_ms",
    "px_match_count",
    "sz_match_count",
    "px_mismatches",
    "sz_mismatches",
    "max_px_diff",
    "max_sz_diff",
    "top_bid_diff",
    "top_ask_diff",
    "mid_price_diff",
    "top5_liquidity_diff_abs",
    "top5_liquidity_diff_pct",
    "imbalance_diff",
]

summary_rows = []
for col in metric_cols:
    s = pd.to_numeric(ok_results_df[col], errors="coerce").dropna()
    if s.empty:
        continue

    summary_rows.append(
        {
            "metric": col,
            "mean": s.mean(),
            "median": s.median(),
            "p95": s.quantile(0.95),
            "max": s.max(),
            "min": s.min(),
        }
    )

validation_summary_df = pd.DataFrame(summary_rows).sort_values("metric").reset_index(drop=True)

print("\n=== VALIDATION SUMMARY ===")
display(validation_summary_df)


# ============================================================
# 7. SIMPLE VERDICT
# ============================================================

def safe_q(series, q):
    s = pd.to_numeric(series, errors="coerce").dropna()
    return np.nan if s.empty else s.quantile(q)

verdict = {
    "n_ok": len(ok_results_df),
    "n_error": int((results_df["status"] == "error").sum()),
    "mid_price_diff_p95": safe_q(ok_results_df["mid_price_diff"], 0.95),
    "top5_liquidity_diff_pct_p95": safe_q(ok_results_df["top5_liquidity_diff_pct"], 0.95),
    "imbalance_diff_p95": safe_q(ok_results_df["imbalance_diff"], 0.95),
    "max_px_diff_worst": pd.to_numeric(ok_results_df["max_px_diff"], errors="coerce").max(),
    "max_sz_diff_worst": pd.to_numeric(ok_results_df["max_sz_diff"], errors="coerce").max(),
    "perfect_price_match_rate": (
        (pd.to_numeric(ok_results_df["px_mismatches"], errors="coerce") == 0).mean()
        if len(ok_results_df) > 0 else np.nan
    ),
}

print("\n=== FINAL VERDICT ===")
for k, v in verdict.items():
    print(f"{k}: {v}")


# ============================================================
# 8. WORST CASES
# ============================================================

print("\n=== WORST BY top5_liquidity_diff_pct ===")
worst_liq_df = ok_results_df.sort_values("top5_liquidity_diff_pct", ascending=False).head(10)
display(worst_liq_df)

print("\n=== WORST BY imbalance_diff ===")
worst_imb_df = ok_results_df.sort_values("imbalance_diff", ascending=False).head(10)
display(worst_imb_df)

print("\n=== WORST BY max_px_diff ===")
worst_px_df = ok_results_df.sort_values("max_px_diff", ascending=False).head(10)
display(worst_px_df)

print("\n=== WORST BY max_sz_diff ===")
worst_sz_df = ok_results_df.sort_values("max_sz_diff", ascending=False).head(10)
display(worst_sz_df)


# ============================================================
# 9. OPTIONAL: SHOW ONE BAD CASE IN DETAIL
# ============================================================

def print_case_report(case: dict):
    summary = case["summary"]
    quality = case["quality"]
    compare_df = case["compare_df"]

    print("\n" + "=" * 60)
    print("ORDERBOOK CASE REPORT")
    print("=" * 60)
    print(f"snapshot_ts      : {summary['snapshot_ts']}")
    print(f"reconstructed_ts : {summary['reconstructed_ts']}")
    print(f"time_delta_ms    : {summary['time_delta_ms']}")
    print(f"px_match_count   : {summary['px_match_count']}")
    print(f"sz_match_count   : {summary['sz_match_count']}")
    print(f"max_px_diff      : {summary['max_px_diff']}")
    print(f"max_sz_diff      : {summary['max_sz_diff']}")
    print(f"mid_price_diff   : {quality['mid_price_diff']}")
    print(f"liq_diff_pct     : {quality['topN_liquidity_diff_pct']}")
    print(f"imbalance_diff   : {quality['imbalance_diff']}")
    print("=" * 60)
    display(compare_df)

# пример:
# if bad_cases:
#     print_case_report(bad_cases[0])

window_start: 2026-03-22 10:00:00+00:00
window_end  : 2026-03-22 11:00:00+00:00
reconstructed rows: 36001
real snapshots in window: 117
sampled snapshots: 117

     ts_event_ms                     ts_event_utc
0  1774173609907 2026-03-22 10:00:09.907000+00:00
1  1774173640707 2026-03-22 10:00:40.707000+00:00
2  1774173671407 2026-03-22 10:01:11.407000+00:00
3  1774173702307 2026-03-22 10:01:42.307000+00:00
4  1774173733007 2026-03-22 10:02:13.007000+00:00

validated points: 117

,snapshot_ms,snapshot_ts,reconstructed_ts,anchor_snapshot_ts,time_delta_ms,px_match_count,sz_match_count,px_mismatches,sz_mismatches,max_px_diff,max_sz_diff,top_bid_diff,top_ask_diff,mid_price_diff,top5_liquidity_diff_abs,top5_liquidity_diff_pct,imbalance_diff,status,error
0,1774173609907,2026-03-22 10:00:09.907000+00:00,2026-03-22 10:00:09.900000+00:00,2026-03-22 09:59:39.307000+00:00,7.0,20,18,0,2,0.0,0.72,0.0,0.0,0.0,0.00,0.000000,0.000000,ok,None
1,1774173640707,2026-03-22 10:00:40.707000+00:00,2026-03-22 10:00:40.700000+00:00,2026-03-22 10:00:09.907000+00:00,7.0,20,15,0,5,0.0,1.46,0.0,0.0,0.0,1.51,0.002647,0.002292,ok,None
2,1774173671407,2026-03-22 10:01:11.407000+00:00,2026-03-22 10:01:11.400000+00:00,2026-03-22 10:00:40.707000+00:00,7.0,20,19,0,1,0.0,0.07,0.0,0.0,0.0,0.07,0.001094,0.000135,ok,None
3,1774173702307,2026-03-22 10:01:42.307000+00:00,2026-03-22 10:01:42.300000+00:00,2026-03-22 10:01:11.407000+00:00,7.0,20,18,0,2,0.0,10.73,0.0,0.0,0.0,11.63,0.024857,0.023985,ok,None
4,1774173733007,2026-03-22 10:02:13.007000+00:00,2026-03-22 10:02:13+00:00,2026-03-22 10:01:42.307000+00:00,7.0,20,17,0,3,0.0,29.09,0.0,0.0,0.0,29.13,0.017886,0.000241,ok,None

successful validations: 117
failed validations     : 0

=== VALIDATION SUMMARY ===

,metric,mean,median,p95,max,min
0,imbalance_diff,0.043384,0.000277,0.147669,1.462790,0.0
1,max_px_diff,0.110256,0.000000,0.600000,2.100000,0.0
2,max_sz_diff,31.966581,1.460000,101.520000,1387.340000,0.0
3,mid_price_diff,0.001709,0.000000,0.000000,0.200000,0.0
4,px_match_count,18.649573,20.000000,20.000000,20.000000,0.0
5,px_mismatches,1.350427,0.000000,8.000000,20.000000,0.0
6,sz_match_count,17.017094,18.000000,20.000000,20.000000,2.0
7,sz_mismatches,2.982906,2.000000,10.200000,18.000000,0.0
8,time_delta_ms,8.760684,9.000000,9.000000,9.000000,7.0
9,top5_liquidity_diff_abs,21.562051,0.520000,93.236000,802.600000,0.0
10,top5_liquidity_diff_pct,0.112738,0.001416,0.585405,2.264181,0.0
11,top_ask_diff,0.001709,0.000000,0.000000,0.200000,0.0
12,top_bid_diff,0.001709,0.000000,0.000000,0.200000,0.0

=== FINAL VERDICT ===
n_ok: 117
n_error: 0
mid_price_diff_p95: 0.0
top5_liquidity_diff_pct_p95: 0.5854047010248392
imbalance_diff_p95: 0.14766869377974565
max_px_diff_worst: 2.1000000000058208
max_sz_diff_worst: 1387.3400000000001
perfect_price_match_rate: 0.7948717948717948

=== WORST BY top5_liquidity_diff_pct ===

,snapshot_ms,snapshot_ts,reconstructed_ts,anchor_snapshot_ts,time_delta_ms,px_match_count,sz_match_count,px_mismatches,sz_mismatches,max_px_diff,max_sz_diff,top_bid_diff,top_ask_diff,mid_price_diff,top5_liquidity_diff_abs,top5_liquidity_diff_pct,imbalance_diff,status,error
21,1774174257809,2026-03-22 10:10:57.809000+00:00,2026-03-22 10:10:57.800000+00:00,2026-03-22 10:10:27.109000+00:00,9.0,20,18,0,2,0.0,107.48,0.0,0.0,0.0,159.93,2.264181,0.404465,ok,None
70,1774175766509,2026-03-22 10:36:06.509000+00:00,2026-03-22 10:36:06.500000+00:00,2026-03-22 10:35:35.809000+00:00,9.0,0,2,20,18,1.5,439.94,0.2,0.2,0.2,802.60,2.159082,1.462790,ok,None
100,1774176690109,2026-03-22 10:51:30.109000+00:00,2026-03-22 10:51:30.100000+00:00,2026-03-22 10:50:59.309000+00:00,9.0,20,17,0,3,0.0,22.48,0.0,0.0,0.0,22.48,1.640876,0.071779,ok,None
64,1774175582009,2026-03-22 10:33:02.009000+00:00,2026-03-22 10:33:02+00:00,2026-03-22 10:32:31.309000+00:00,9.0,20,19,0,1,0.0,45.31,0.0,0.0,0.0,45.31,1.520470,0.333728,ok,None
61,1774175489909,2026-03-22 10:31:29.909000+00:00,2026-03-22 10:31:29.900000+00:00,2026-03-22 10:30:59.209000+00:00,9.0,14,12,6,8,0.1,23.36,0.0,0.0,0.0,32.64,1.308090,0.145124,ok,None
51,1774175182209,2026-03-22 10:26:22.209000+00:00,2026-03-22 10:26:22.200000+00:00,2026-03-22 10:25:51.509000+00:00,9.0,12,9,8,11,0.7,180.12,0.0,0.0,0.0,261.75,0.749597,0.935068,ok,None
11,1774173948607,2026-03-22 10:05:48.607000+00:00,2026-03-22 10:05:48.600000+00:00,2026-03-22 10:05:17.907000+00:00,7.0,8,7,12,13,2.1,69.60,0.0,0.0,0.0,179.51,0.544357,0.323633,ok,None
35,1774174688009,2026-03-22 10:18:08.009000+00:00,2026-03-22 10:18:08+00:00,2026-03-22 10:17:37.409000+00:00,9.0,20,19,0,1,0.0,33.32,0.0,0.0,0.0,33.32,0.257377,0.124110,ok,None
82,1774176136009,2026-03-22 10:42:16.009000+00:00,2026-03-22 10:42:16+00:00,2026-03-22 10:41:45.309000+00:00,9.0,11,13,9,7,0.5,32.85,0.0,0.0,0.0,32.89,0.257126,0.043695,ok,None
5,1774173763707,2026-03-22 10:02:43.707000+00:00,2026-03-22 10:02:43.700000+00:00,2026-03-22 10:02:13.007000+00:00,7.0,20,18,0,2,0.0,21.53,0.0,0.0,0.0,21.58,0.240135,0.079658,ok,None

=== WORST BY imbalance_diff ===

,snapshot_ms,snapshot_ts,reconstructed_ts,anchor_snapshot_ts,time_delta_ms,px_match_count,sz_match_count,px_mismatches,sz_mismatches,max_px_diff,max_sz_diff,top_bid_diff,top_ask_diff,mid_price_diff,top5_liquidity_diff_abs,top5_liquidity_diff_pct,imbalance_diff,status,error
70,1774175766509,2026-03-22 10:36:06.509000+00:00,2026-03-22 10:36:06.500000+00:00,2026-03-22 10:35:35.809000+00:00,9.0,0,2,20,18,1.5,439.94,0.2,0.2,0.2,802.60,2.159082,1.462790,ok,None
51,1774175182209,2026-03-22 10:26:22.209000+00:00,2026-03-22 10:26:22.200000+00:00,2026-03-22 10:25:51.509000+00:00,9.0,12,9,8,11,0.7,180.12,0.0,0.0,0.0,261.75,0.749597,0.935068,ok,None
21,1774174257809,2026-03-22 10:10:57.809000+00:00,2026-03-22 10:10:57.800000+00:00,2026-03-22 10:10:27.109000+00:00,9.0,20,18,0,2,0.0,107.48,0.0,0.0,0.0,159.93,2.264181,0.404465,ok,None
64,1774175582009,2026-03-22 10:33:02.009000+00:00,2026-03-22 10:33:02+00:00,2026-03-22 10:32:31.309000+00:00,9.0,20,19,0,1,0.0,45.31,0.0,0.0,0.0,45.31,1.520470,0.333728,ok,None
11,1774173948607,2026-03-22 10:05:48.607000+00:00,2026-03-22 10:05:48.600000+00:00,2026-03-22 10:05:17.907000+00:00,7.0,8,7,12,13,2.1,69.60,0.0,0.0,0.0,179.51,0.544357,0.323633,ok,None
112,1774177060909,2026-03-22 10:57:40.909000+00:00,2026-03-22 10:57:40.900000+00:00,2026-03-22 10:57:10.409000+00:00,9.0,20,18,0,2,0.0,191.53,0.0,0.0,0.0,191.67,0.188978,0.157849,ok,None
61,1774175489909,2026-03-22 10:31:29.909000+00:00,2026-03-22 10:31:29.900000+00:00,2026-03-22 10:30:59.209000+00:00,9.0,14,12,6,8,0.1,23.36,0.0,0.0,0.0,32.64,1.308090,0.145124,ok,None
8,1774173856507,2026-03-22 10:04:16.507000+00:00,2026-03-22 10:04:16.500000+00:00,2026-03-22 10:03:45.107000+00:00,7.0,16,10,4,10,0.2,52.45,0.0,0.0,0.0,29.03,0.196739,0.139816,ok,None
35,1774174688009,2026-03-22 10:18:08.009000+00:00,2026-03-22 10:18:08+00:00,2026-03-22 10:17:37.409000+00:00,9.0,20,19,0,1,0.0,33.32,0.0,0.0,0.0,33.32,0.257377,0.124110,ok,None
58,1774175397209,2026-03-22 10:29:57.209000+00:00,2026-03-22 10:29:57.200000+00:00,2026-03-22 10:29:26.509000+00:00,9.0,20,19,0,1,0.0,22.53,0.0,0.0,0.0,22.53,0.170269,0.113918,ok,None

=== WORST BY max_px_diff ===

,snapshot_ms,snapshot_ts,reconstructed_ts,anchor_snapshot_ts,time_delta_ms,px_match_count,sz_match_count,px_mismatches,sz_mismatches,max_px_diff,max_sz_diff,top_bid_diff,top_ask_diff,mid_price_diff,top5_liquidity_diff_abs,top5_liquidity_diff_pct,imbalance_diff,status,error
11,1774173948607,2026-03-22 10:05:48.607000+00:00,2026-03-22 10:05:48.600000+00:00,2026-03-22 10:05:17.907000+00:00,7.0,8,7,12,13,2.1,69.60,0.0,0.0,0.0,179.51,0.544357,0.323633,ok,None
70,1774175766509,2026-03-22 10:36:06.509000+00:00,2026-03-22 10:36:06.500000+00:00,2026-03-22 10:35:35.809000+00:00,9.0,0,2,20,18,1.5,439.94,0.2,0.2,0.2,802.60,2.159082,1.462790,ok,None
32,1774174596009,2026-03-22 10:16:36.009000+00:00,2026-03-22 10:16:36+00:00,2026-03-22 10:16:05.409000+00:00,9.0,13,11,7,9,1.4,130.65,0.0,0.0,0.0,94.90,0.107345,0.042601,ok,None
51,1774175182209,2026-03-22 10:26:22.209000+00:00,2026-03-22 10:26:22.200000+00:00,2026-03-22 10:25:51.509000+00:00,9.0,12,9,8,11,0.7,180.12,0.0,0.0,0.0,261.75,0.749597,0.935068,ok,None
13,1774174009707,2026-03-22 10:06:49.707000+00:00,2026-03-22 10:06:49.700000+00:00,2026-03-22 10:06:19.107000+00:00,7.0,11,9,9,11,0.6,41.41,0.0,0.0,0.0,1.35,0.006588,0.005787,ok,None
78,1774176012709,2026-03-22 10:40:12.709000+00:00,2026-03-22 10:40:12.700000+00:00,2026-03-22 10:39:41.409000+00:00,9.0,15,16,5,4,0.6,40.87,0.0,0.0,0.0,0.08,0.000110,0.000107,ok,None
106,1774176875509,2026-03-22 10:54:35.509000+00:00,2026-03-22 10:54:35.500000+00:00,2026-03-22 10:54:04.809000+00:00,9.0,13,10,7,10,0.6,12.58,0.0,0.0,0.0,12.86,0.016020,0.015461,ok,None
43,1774174935809,2026-03-22 10:22:15.809000+00:00,2026-03-22 10:22:15.800000+00:00,2026-03-22 10:21:45.209000+00:00,9.0,12,12,8,8,0.6,76.30,0.0,0.0,0.0,0.36,0.000782,0.000422,ok,None
50,1774175151509,2026-03-22 10:25:51.509000+00:00,2026-03-22 10:25:51.500000+00:00,2026-03-22 10:25:20.409000+00:00,9.0,18,15,2,5,0.5,2.25,0.0,0.0,0.0,0.51,0.000941,0.000684,ok,None
80,1774176074209,2026-03-22 10:41:14.209000+00:00,2026-03-22 10:41:14.200000+00:00,2026-03-22 10:40:43.509000+00:00,9.0,15,12,5,8,0.5,1387.34,0.0,0.0,0.0,0.15,0.000516,0.000466,ok,None

=== WORST BY max_sz_diff ===

,snapshot_ms,snapshot_ts,reconstructed_ts,anchor_snapshot_ts,time_delta_ms,px_match_count,sz_match_count,px_mismatches,sz_mismatches,max_px_diff,max_sz_diff,top_bid_diff,top_ask_diff,mid_price_diff,top5_liquidity_diff_abs,top5_liquidity_diff_pct,imbalance_diff,status,error
80,1774176074209,2026-03-22 10:41:14.209000+00:00,2026-03-22 10:41:14.200000+00:00,2026-03-22 10:40:43.509000+00:00,9.0,15,12,5,8,0.5,1387.34,0.0,0.0,0.0,0.15,0.000516,0.000466,ok,None
70,1774175766509,2026-03-22 10:36:06.509000+00:00,2026-03-22 10:36:06.500000+00:00,2026-03-22 10:35:35.809000+00:00,9.0,0,2,20,18,1.5,439.94,0.2,0.2,0.2,802.60,2.159082,1.462790,ok,None
112,1774177060909,2026-03-22 10:57:40.909000+00:00,2026-03-22 10:57:40.900000+00:00,2026-03-22 10:57:10.409000+00:00,9.0,20,18,0,2,0.0,191.53,0.0,0.0,0.0,191.67,0.188978,0.157849,ok,None
51,1774175182209,2026-03-22 10:26:22.209000+00:00,2026-03-22 10:26:22.200000+00:00,2026-03-22 10:25:51.509000+00:00,9.0,12,9,8,11,0.7,180.12,0.0,0.0,0.0,261.75,0.749597,0.935068,ok,None
32,1774174596009,2026-03-22 10:16:36.009000+00:00,2026-03-22 10:16:36+00:00,2026-03-22 10:16:05.409000+00:00,9.0,13,11,7,9,1.4,130.65,0.0,0.0,0.0,94.90,0.107345,0.042601,ok,None
21,1774174257809,2026-03-22 10:10:57.809000+00:00,2026-03-22 10:10:57.800000+00:00,2026-03-22 10:10:27.109000+00:00,9.0,20,18,0,2,0.0,107.48,0.0,0.0,0.0,159.93,2.264181,0.404465,ok,None
108,1774176936909,2026-03-22 10:55:36.909000+00:00,2026-03-22 10:55:36.900000+00:00,2026-03-22 10:55:06.109000+00:00,9.0,12,10,8,10,0.5,100.03,0.0,0.0,0.0,6.16,0.015735,0.005326,ok,None
18,1774174164409,2026-03-22 10:09:24.409000+00:00,2026-03-22 10:09:24.400000+00:00,2026-03-22 10:08:53.909000+00:00,9.0,14,14,6,6,0.2,92.77,0.0,0.0,0.0,92.82,0.078341,0.027700,ok,None
43,1774174935809,2026-03-22 10:22:15.809000+00:00,2026-03-22 10:22:15.800000+00:00,2026-03-22 10:21:45.209000+00:00,9.0,12,12,8,8,0.6,76.30,0.0,0.0,0.0,0.36,0.000782,0.000422,ok,None
11,1774173948607,2026-03-22 10:05:48.607000+00:00,2026-03-22 10:05:48.600000+00:00,2026-03-22 10:05:17.907000+00:00,7.0,8,7,12,13,2.1,69.60,0.0,0.0,0.0,179.51,0.544357,0.323633,ok,None